<?php

namespace App\Services;

use App\Models\ProxyRule;

/**
 * NginxConfigGenerator - turns a ProxyRule into a syntactically valid
 * nginx server/location block.
 *
 * Supports: http, websocket, tcp, grpc, sse, redirect.
 */
class NginxConfigGenerator
{
    public function generate(ProxyRule $rule): string
    {
        return match ($rule->type) {
            ProxyRule::TYPE_WEBSOCKET => $this->websocket($rule),
            ProxyRule::TYPE_TCP       => $this->tcp($rule),
            ProxyRule::TYPE_GRPC      => $this->grpc($rule),
            ProxyRule::TYPE_REDIRECT  => $this->redirect($rule),
            default                   => $this->http($rule),
        };
    }

    protected function http(ProxyRule $rule): string
    {
        $origin  = $rule->originServer;
        $domain  = $rule->domain?->domain;
        $upstream = sprintf('upstream_%d', $rule->id);

        $path = $this->locationPath($rule);
        $http2 = $rule->http2_enabled ? 'http2 on;' : '';
        $h3 = $rule->http3_enabled ? 'add_header Alt-Svc \'h3=":443"\';' : '';

        return <<<NGINX
# Auto-generated by Xerex Panel — rule #{$rule->id}
upstream {$upstream} {
    {$origin->host}:{$origin->port};
    keepalive 32;
}

server {
    listen {$rule->listen_port} ssl {$http2};
    server_name {$domain};

    ssl_certificate     /etc/letsencrypt/live/{$domain}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{$domain}/privkey.pem;

    {$h3}

    {$path}
    proxy_pass {$origin->ssl_enabled ? 'https' : 'http'}://{$upstream};

    proxy_http_version 1.1;
    proxy_set_header Host              \$host;
    proxy_set_header X-Real-IP         \$remote_addr;
    proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_set_header Connection        "";

    proxy_connect_timeout {$origin->connect_timeout}s;
    proxy_send_timeout    {$origin->send_timeout}s;
    proxy_read_timeout    {$origin->read_timeout}s;

{$this->requestHeaders($rule)}
{$this->responseHeaders($rule)}
}
NGINX;
    }

    protected function websocket(ProxyRule $rule): string
    {
        $origin  = $rule->originServer;
        $domain  = $rule->domain?->domain;
        $path = $this->locationPath($rule);
        $target = $origin->ssl_enabled ? 'https' : 'http';

        return <<<NGINX
# Auto-generated by Xerex Panel — WebSocket rule #{$rule->id}
server {
    listen {$rule->listen_port} ssl;
    server_name {$domain};
    ssl_certificate     /etc/letsencrypt/live/{$domain}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{$domain}/privkey.pem;

    {$path}
    proxy_pass {$target}://{$origin->host}:{$origin->port};

    proxy_http_version 1.1;
    proxy_set_header Upgrade           \$http_upgrade;
    proxy_set_header Connection        "upgrade";
    proxy_set_header Host              \$host;
    proxy_set_header X-Real-IP         \$remote_addr;
    proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;

    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
}
NGINX;
    }

    protected function tcp(ProxyRule $rule): string
    {
        $origin = $rule->originServer;
        return <<<NGINX
# Auto-generated by Xerex Panel — TCP/stream rule #{$rule->id}
stream {
    server {
        listen {$rule->listen_port};
        proxy_pass {$origin->host}:{$origin->port};
        proxy_timeout {$origin->read_timeout}s;
        proxy_connect_timeout {$origin->connect_timeout}s;
    }
}
NGINX;
    }

    protected function grpc(ProxyRule $rule): string
    {
        $origin = $rule->originServer;
        $domain = $rule->domain?->domain;
        $path = $this->locationPath($rule);
        $target = $origin->ssl_enabled ? 'https' : 'http';

        return <<<NGINX
# Auto-generated by Xerex Panel — gRPC rule #{$rule->id}
server {
    listen {$rule->listen_port} ssl http2;
    server_name {$domain};
    ssl_certificate     /etc/letsencrypt/live/{$domain}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{$domain}/privkey.pem;

    {$path}
    grpc_pass {$target}://{$origin->host}:{$origin->port};

    grpc_connect_timeout {$origin->connect_timeout}s;
    grpc_read_timeout    {$origin->read_timeout}s;
    grpc_send_timeout    {$origin->send_timeout}s;
}
NGINX;
    }

    protected function redirect(ProxyRule $rule): string
    {
        $target = $rule->headers_request['redirect_to'] ?? 'https://example.com';
        return <<<NGINX
server {
    listen {$rule->listen_port};
    server_name {$rule->domain?->domain};
    return 301 {$target};
}
NGINX;
    }

    protected function locationPath(ProxyRule $rule): string
    {
        return match ($rule->path_match_type) {
            ProxyRule::PATH_EXACT  => "location = {$rule->path} {",
            ProxyRule::PATH_REGEX  => "location ~ '{$rule->path}' {",
            default                => "location {$rule->path} {",
        };
    }

    protected function requestHeaders(ProxyRule $rule): string
    {
        if (! $rule->headers_request) return '';
        $out = '';
        foreach ($rule->headers_request as $name => $value) {
            $out .= "    proxy_set_header {$name} \"{$value}\";\n";
        }
        return rtrim($out);
    }

    protected function responseHeaders(ProxyRule $rule): string
    {
        if (! $rule->headers_response) return '';
        $out = '';
        foreach ($rule->headers_response as $name => $value) {
            $out .= "    add_header {$name} \"{$value}\" always;\n";
        }
        return rtrim($out);
    }
}
