#!/usr/bin/env bash
# install.sh — Install / upgrade the Xerex Edge Agent on a Linux host.
#
# Usage:
#   curl -fsSL https://github.com/monajiane/xerex-panel/releases/latest/download/install.sh | sudo bash -s -- \
#       --panel-url https://panel.example.com \
#       --token <AGENT_TOKEN> \
#       --edge-name edge-fra-01
#
# Or, after a manual `make build`:
#   sudo ./scripts/install.sh --panel-url ... --token ...
#
# This script is intentionally idempotent: re-running it on an already
# installed box just replaces the binary and refreshes the systemd unit.

set -euo pipefail

PANEL_URL=""
TOKEN=""
EDGE_NAME=""
VERSION="${XEREX_VERSION:-1.0.0}"
BIN="/usr/local/bin/xerex-agent"
CONF_DIR="/etc/xerex"
CONF_FILE="${CONF_DIR}/agent.yaml"
SERVICE_FILE="/etc/systemd/system/xerex-agent.service"
LOG_DIR="/var/log/xerex"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --panel-url)   PANEL_URL="$2"; shift 2 ;;
        --token)       TOKEN="$2"; shift 2 ;;
        --edge-name)   EDGE_NAME="$2"; shift 2 ;;
        --version)     VERSION="$2"; shift 2 ;;
        --config)      CONF_FILE="$2"; shift 2 ;;
        -h|--help)
            sed -n '2,18p' "$0"
            exit 0
            ;;
        *)
            echo "Unknown arg: $1" >&2
            exit 64
            ;;
    esac
done

if [[ $EUID -ne 0 ]]; then
    echo "Please run as root (e.g. with sudo)." >&2
    exit 1
fi

if [[ -z "$PANEL_URL" || -z "$TOKEN" ]]; then
    echo "ERROR: --panel-url and --token are required." >&2
    exit 1
fi

# 1. Detect architecture
ARCH="$(uname -m)"
case "$ARCH" in
    x86_64)         GOARCH=amd64 ;;
    aarch64|arm64)  GOARCH=arm64 ;;
    armv7l)         GOARCH=arm ;;
    *)
        echo "Unsupported architecture: $ARCH" >&2
        exit 1
        ;;
esac
echo ">> Detected arch: $GOARCH"

# 2. Install nginx if missing (we depend on it for proxying)
if ! command -v nginx >/dev/null 2>&1; then
    echo ">> nginx not found, attempting to install"
    if command -v apt-get >/dev/null 2>&1; then
        DEBIAN_FRONTEND=noninteractive apt-get update -y
        DEBIAN_FRONTEND=noninteractive apt-get install -y nginx
    elif command -v dnf >/dev/null 2>&1; then
        dnf install -y nginx
    elif command -v yum >/dev/null 2>&1; then
        yum install -y nginx
    else
        echo "Could not install nginx automatically; please install it manually." >&2
        exit 1
    fi
fi

# 3. Lay out directories
mkdir -p "$CONF_DIR" "$LOG_DIR"

# 4. Place the binary
if [[ ! -f "$BIN" ]]; then
    echo ">> Installing binary to $BIN"
    if [[ -f "./build/xerex-agent-linux-${GOARCH}" ]]; then
        install -m 0755 "./build/xerex-agent-linux-${GOARCH}" "$BIN"
    elif [[ -f "./xerex-agent" ]]; then
        install -m 0755 "./xerex-agent" "$BIN"
    else
        echo "ERROR: binary not found. Build first with 'make build' or download from releases." >&2
        exit 1
    fi
else
    echo ">> Replacing existing binary at $BIN"
    if [[ -f "./build/xerex-agent-linux-${GOARCH}" ]]; then
        install -m 0755 "./build/xerex-agent-linux-${GOARCH}" "$BIN"
    elif [[ -f "./xerex-agent" ]]; then
        install -m 0755 "./xerex-agent" "$BIN"
    fi
fi

# 5. Render the default config file (only if missing)
if [[ ! -f "$CONF_FILE" ]]; then
    if [[ -z "$EDGE_NAME" ]]; then
        EDGE_NAME="$(hostname)"
    fi
    cat > "$CONF_FILE" <<EOF
# Xerex Edge Agent configuration
# Generated by install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
agent_token: "${TOKEN}"
panel_url:   "${PANEL_URL}"
edge_name:   "${EDGE_NAME}"
log_level:   info
log_format:  console
EOF
    chmod 0600 "$CONF_FILE"
    echo ">> Wrote $CONF_FILE (mode 0600)"
else
    # Update panel_url / token if provided and existing values differ
    tmp=$(mktemp)
    awk -v url="$PANEL_URL" -v token="$TOKEN" '
        /^panel_url:/   { print "panel_url:   \"" url "\"";   next }
        /^agent_token:/ { print "agent_token: \"" token "\""; next }
        { print }
    ' "$CONF_FILE" > "$tmp" && mv "$tmp" "$CONF_FILE"
    chmod 0600 "$CONF_FILE"
    echo ">> Refreshed credentials in $CONF_FILE"
fi

# 6. Install the systemd unit
install -m 0644 ./scripts/xerex-agent.service "$SERVICE_FILE"
systemctl daemon-reload
systemctl enable xerex-agent
systemctl restart xerex-agent

echo
echo "✓ Xerex Edge Agent installed and started"
echo "  - Binary:  $BIN"
echo "  - Config:  $CONF_FILE"
echo "  - Logs:    $LOG_DIR + journalctl -u xerex-agent -f"
echo
echo "Useful commands:"
echo "  systemctl status  xerex-agent"
echo "  journalctl -u xerex-agent -f"
echo "  nginx -t && systemctl reload nginx"
